### ISSUE TITLE
feat: improve boss timers with buttons to adjust timing

### ISSUE THREAD

**Issue by Tschis** [PawelKusnierek/TibiaPal#38]
Sometimes you can get caught up in a boss frenzy, or just forget to click on the boss immediately after killing it, which means the actual timer might be slightly off.

Would be cool to have buttons  to adjust the time, at least in a minor fashion. 
For example: `+` and `-` buttons that change the timer in 15min ranges

**Comment by PawelKusnierek** [comment]
Hey, thanks for the suggestion. Indeed I can definitely see the use in that! 
I will need to investigate the ease with which this could be implemented, but given that I don't think this is too critical, it will likely be pretty low on the priority list depending on the effort required.

Thanks for raising!

**Comment by PawelKusnierek** [comment]
Will not be worked on given boss timers are not really used anymore as CipSoft implemented it in game.
