### ISSUE TITLE
Show/Save records of TibiaLootSplit to see experience, waste, loot, number of team members

### ISSUE THREAD

**Issue by ddivito** [PawelKusnierek/TibiaPal#40]
You may be able to add a history of the last 20 party hunts, to get waste, loot, profit and which monsters killed

**Comment by PawelKusnierek** [comment]
Thanks I will try when I have time

**Comment by ddivito** [comment]
The idea is to see how much experience, waste, loot, how big the team is, and know what they hunt, at least the last 10 or 20 records so that you do not have to store information on your site and hosting does not become more expensive although it would be great to see something like a summary like nabbot does about this kind of thing at the end of the year

**Comment by PawelKusnierek** [comment]
The party hunt analyser does not contain information about monsters killed so will not be able to store that

**Comment by ddivito** [comment]
There was a website for that tibiahuntingrecords.com but this down, users could share data from the hunting area such as exp, profit, charm, preys, skills, vocation and level

**Comment by ddivito** [comment]
Too bad it fell, I liked the idea, also the characters could comment and give their opinions and super useful experience

**Comment by PawelKusnierek** [comment]
I will have a think about feature like this, but this is a whole 'new' feature that would need to be separate from 'TibiaLootSplit' :)

**Comment by PawelKusnierek** [comment]
@ddivito hey - today this has been implemented as well as I could with the data present in party hunt analyser. I hope you find it useful.
