### ISSUE TITLE
Last Planegazer is 7d CD, not 20h

### ISSUE THREAD

**Issue by Tschis** [PawelKusnierek/TibiaPal#44]
Based on wikis
- https://www.tibiawiki.com.br/wiki/Mysterious_Ornate_Chest_Quest#4.C2.BA_Etapa:_Planegazers
- https://tibia.fandom.com/wiki/Opticording_Sphere_Quest#Dolis_-_The_Last_Planegazer

**Comment by PawelKusnierek** [comment]
Thanks very much, fixed.
