### ISSUE TITLE
tibia forum crawler with search funtion

### ISSUE THREAD

**Issue by ddivito** [PawelKusnierek/TibiaPal#47]
a new function for tibiapal.com, tibia forum crawler in text to make it light where you can search for the topics and comments, a function that cipsoft refuses to do for the official forum site without giving clear reasons, there is currently a website that does this but stopped working 2 years ago, tibiacommunity and there is no indication that they will fix it. 

example  [https://imgur.com/a/QjW7z2X](https://imgur.com/a/QjW7z2X)

**Comment by PawelKusnierek** [comment]
Hey, this is an amazing idea that I would love to implement some day. However, this requires a rather significant re-design of the whole back-end. I would need to implement some crawlers which with the current setup isn't possible.

I'm planning a pretty big redesign in the coming months and with that I will hopefully be able to implement such a feature, but I'm afraid as it's going to be quite a big process it's still some months away. 

Thanks!

**Comment by PawelKusnierek** [comment]
Closing this for now as it's unfeasible until CipSoft implement a forum API.
