### ISSUE TITLE
stamina calc

### ISSUE THREAD

**Issue by PawelKusnierek** [PawelKusnierek/TibiaPal#58]
reads your Windows clock and tells you what time it will be to have to desired stamina, and not only how many hours and minutes it will take to recover

e.g. 
Will be ready: Tomorrow at 7:56 AM

**Comment by kosaa** [comment]
https://github.com/PawelKusnierek/TibiaPal/pull/62

**Comment by PawelKusnierek** [comment]
thanks very much, could I ask for a minor improvement please, instead of displaying the date as e.g. 25/03/2022, could it instead be displayed more like 25th March 2022, or something like this?

I don't want there to be any ambiguity with MM/DD/YY or DD/MM/YY format, as I have a few american users :)

**Comment by kosaa** [comment]
used method `toLocaleString` depends on your local settings, for example `en-US` will format `MM/DD/YYYY`,`en-GB` use `DD/MM/YYYY`, polish locale are using dots

you still think that it should be unified?

**Comment by PawelKusnierek** [comment]
Ah I forgot. Fair enough, agreed, closing the issue. Thanks!
