### ISSUE TITLE
send requests via a proxy with static IP so that tibiapal requests can be whitelisted by cipsoft

### ISSUE THREAD

**Issue by PawelKusnierek** [PawelKusnierek/TibiaPal#80]

**Comment by divinity76** [comment]
can you elaborate? why are you being banned?

**Comment by PawelKusnierek** [comment]
Sure. By default ALL scraping of tibia.com is not allowed and unless your IP is whitelisted you will be automatically banned by CipSoft.

As a fansite, I have an option of requesting my IP to be whitelisted so I can scrape tibia.com without getting banned.

My hosting provider is PythonAnywhere which is hosted on AWS and by default has a non-static IP address, which means I'm not able to give CipSoft a 'single' IP address to whitelist.

I therefore need to investigate how to send my requests via some proxy that will allow me to have a static IP from the perspective of CipSoft, so that they can whitelist it and then I will be able to freely scrape tibia.com

**Comment by divinity76** [comment]
do you already have a scraper, or do you want to make one?

**Comment by PawelKusnierek** [comment]
I plan to make one eventually, so just planning for the future

**Comment by divinity76** [comment]
do you have a ssh public key you can share with me?
